"""make user profile fields optional

Revision ID: 25b5ad433aa3
Revises: d5af130368d0
Create Date: 2026-06-20 15:38:19.530730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b5ad433aa3'
down_revision: Union[str, Sequence[str], None] = 'd5af130368d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'stack',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'salary_expectation',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'work_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'work_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'salary_expectation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'stack',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
