"""add resume_text to user

Revision ID: 8b981e7f28d9
Revises: c0a79ad7bb53
Create Date: 2026-06-23 09:32:20.312261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b981e7f28d9'
down_revision: Union[str, Sequence[str], None] = 'c0a79ad7bb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_text')
    # ### end Alembic commands ###
