"""make company nullable

Revision ID: c0a79ad7bb53
Revises: 86f2a887b337
Create Date: 2026-06-22 16:02:21.863503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a79ad7bb53'
down_revision: Union[str, Sequence[str], None] = '86f2a887b337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
