"""make salary type experience_years nullable

Revision ID: f36af4498825
Revises: 6da0ae1217bb
Create Date: 2026-06-22 11:33:23.828545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36af4498825'
down_revision: Union[str, Sequence[str], None] = '6da0ae1217bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('vacancies', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vacancies', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vacancies', 'salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
